"""
Tests for AI chat endpoint.

Mocks the EDSAgent so no real LLM calls are made.
"""

import json
import pytest
from unittest.mock import patch, MagicMock
from fastapi import HTTPException


# ============================================
# Mock helpers
# ============================================

def _mock_agent_response(content="Here are the results.", sql=None, docs=None):
    """Create a mock AgentResponse-like object."""
    mock = MagicMock()
    mock.content = content
    mock.sql_generated = sql
    mock.docs_retrieved = docs or []
    return mock


def _mock_agent(session_id="test-session-123"):
    """Create a mock EDSAgent."""
    agent = MagicMock()
    agent.current_session_id = session_id
    agent.chat.return_value = _mock_agent_response()
    agent.start_session.return_value = session_id
    return agent


# ============================================
# Chat Endpoint Tests
# ============================================

class TestChatEndpoint:
    """Test POST /api/chat."""

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_send_message_new_session(self, mock_get_agent, test_client):
        """New message without session_id creates a new session."""
        agent = _mock_agent()
        mock_get_agent.return_value = (agent, "test-session-123")

        response = test_client.post("/api/chat", json={
            "message": "What tables exist in the database?",
        })
        assert response.status_code == 200
        data = response.json()
        assert data["session_id"] == "test-session-123"
        assert data["response"] == "Here are the results."
        agent.chat.assert_called_once_with(
            message="What tables exist in the database?",
            include_docs=True,
        )

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_send_message_existing_session(self, mock_get_agent, test_client):
        """Message with session_id continues conversation."""
        agent = _mock_agent("existing-session")
        mock_get_agent.return_value = (agent, "existing-session")

        response = test_client.post("/api/chat", json={
            "message": "Now show only active ones",
            "session_id": "existing-session",
        })
        assert response.status_code == 200
        data = response.json()
        assert data["session_id"] == "existing-session"
        mock_get_agent.assert_called_once_with("existing-session")

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_response_includes_sql(self, mock_get_agent, test_client):
        """SQL generated by the agent is included in response."""
        agent = _mock_agent()
        agent.chat.return_value = _mock_agent_response(
            content="Top 5 vendors by item count:",
            sql="SELECT TOP 5 v.Name, COUNT(*) FROM Items i JOIN Vendors v ...",
        )
        mock_get_agent.return_value = (agent, "test-session-123")

        response = test_client.post("/api/chat", json={
            "message": "Top 5 vendors",
        })
        assert response.status_code == 200
        data = response.json()
        assert "SELECT TOP 5" in data["sql_generated"]

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_response_includes_docs(self, mock_get_agent, test_client):
        """Documentation snippets are included in response."""
        agent = _mock_agent()
        agent.chat.return_value = _mock_agent_response(
            content="Based on the docs...",
            docs=["Items table stores product catalog entries"],
        )
        mock_get_agent.return_value = (agent, "test-session-123")

        response = test_client.post("/api/chat", json={
            "message": "Explain the Items table",
        })
        assert response.status_code == 200
        data = response.json()
        assert len(data["docs_retrieved"]) == 1

    def test_empty_message(self, test_client):
        """Empty message returns 422."""
        response = test_client.post("/api/chat", json={
            "message": "",
        })
        assert response.status_code == 422

    def test_missing_message(self, test_client):
        """Missing message field returns 422."""
        response = test_client.post("/api/chat", json={})
        assert response.status_code == 422

    def test_message_too_long(self, test_client):
        """Message over 2000 characters returns 422."""
        response = test_client.post("/api/chat", json={
            "message": "x" * 2001,
        })
        assert response.status_code == 422

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", False)
    def test_disabled_returns_503(self, test_client):
        """When API key is not configured, returns 503."""
        response = test_client.post("/api/chat", json={
            "message": "hello",
        })
        assert response.status_code == 503
        assert "not available" in response.json()["detail"]

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_agent_exception_returns_500(self, mock_get_agent, test_client):
        """When agent raises an exception, returns 500."""
        agent = _mock_agent()
        agent.chat.side_effect = RuntimeError("LLM provider unavailable")
        mock_get_agent.return_value = (agent, "test-session-123")

        response = test_client.post("/api/chat", json={
            "message": "What tables exist?",
        })
        assert response.status_code == 500
        assert "error" in response.json()["detail"].lower()


# ============================================
# End Session Tests
# ============================================

class TestEndSession:
    """Test DELETE /api/chat/{session_id}."""

    @patch("api.routes.ai_chat._remove_agent")
    def test_end_session(self, mock_remove, test_client):
        """DELETE ends the session and returns ok."""
        response = test_client.delete("/api/chat/test-session-123")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "ok"
        mock_remove.assert_called_once_with("test-session-123")

    @patch("api.routes.ai_chat._remove_agent")
    def test_end_nonexistent_session(self, mock_remove, test_client):
        """DELETE on a nonexistent session still returns ok (idempotent)."""
        response = test_client.delete("/api/chat/nonexistent-id")
        assert response.status_code == 200
        assert response.json()["status"] == "ok"


# ============================================
# Streaming Endpoint Tests
# ============================================

class TestChatStream:
    """Test POST /api/chat/stream (SSE streaming)."""

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_stream_returns_sse(self, mock_get_agent, test_client):
        """Streaming endpoint returns SSE chunks followed by done event."""
        agent = _mock_agent()
        agent.chat_stream.return_value = iter(["Hello", " world", "!"])
        mock_get_agent.return_value = (agent, "stream-session-1")

        response = test_client.post("/api/chat/stream", json={
            "message": "Say hello",
        })
        assert response.status_code == 200
        assert "text/event-stream" in response.headers["content-type"]

        # Parse SSE events from response body
        events = []
        for line in response.text.strip().split("\n\n"):
            if line.startswith("data: "):
                events.append(json.loads(line[6:]))

        # Should have 3 chunk events + 1 done event
        assert len(events) == 4
        assert events[0] == {"type": "chunk", "content": "Hello"}
        assert events[1] == {"type": "chunk", "content": " world"}
        assert events[2] == {"type": "chunk", "content": "!"}
        assert events[3]["type"] == "done"
        assert events[3]["session_id"] == "stream-session-1"

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", False)
    def test_stream_disabled_returns_503(self, test_client):
        """When API key is not configured, streaming returns 503."""
        response = test_client.post("/api/chat/stream", json={
            "message": "hello",
        })
        assert response.status_code == 503
        assert "not available" in response.json()["detail"]

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_stream_error_event(self, mock_get_agent, test_client):
        """When agent raises mid-stream, an error event is sent."""
        agent = _mock_agent()
        def _exploding_stream(**kwargs):
            yield "partial"
            raise RuntimeError("LLM crashed")
        agent.chat_stream.side_effect = _exploding_stream
        mock_get_agent.return_value = (agent, "stream-session-err")

        response = test_client.post("/api/chat/stream", json={
            "message": "Will fail mid-stream",
        })
        assert response.status_code == 200

        events = []
        for line in response.text.strip().split("\n\n"):
            if line.startswith("data: "):
                events.append(json.loads(line[6:]))

        # Should have 1 chunk + 1 error
        assert len(events) == 2
        assert events[0] == {"type": "chunk", "content": "partial"}
        assert events[1]["type"] == "error"
        # Error messages are user-friendly (not raw exception text)
        assert "message" in events[1]
        assert len(events[1]["message"]) > 0

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_stream_connection_error_message(self, mock_get_agent, test_client):
        """Connection/timeout errors get a user-friendly message."""
        agent = _mock_agent()
        def _timeout_stream(**kwargs):
            raise ConnectionError("connection timeout after 30s")
        agent.chat_stream.side_effect = _timeout_stream
        mock_get_agent.return_value = (agent, "stream-session-conn")

        response = test_client.post("/api/chat/stream", json={
            "message": "Will timeout",
        })
        events = []
        for line in response.text.strip().split("\n\n"):
            if line.startswith("data: "):
                events.append(json.loads(line[6:]))

        assert len(events) == 1
        assert events[0]["type"] == "error"
        assert "connecting" in events[0]["message"].lower() or "trouble" in events[0]["message"].lower()

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_stream_status_events(self, mock_get_agent, test_client):
        """Status markers from agent are converted to status events."""
        agent = _mock_agent()
        agent.chat_stream.return_value = iter([
            "[STATUS:Searching catalog...]",
            "[STATUS:]",
            "Here are the results.",
        ])
        mock_get_agent.return_value = (agent, "stream-session-status")

        response = test_client.post("/api/chat/stream", json={
            "message": "Find pencils",
        })
        events = []
        for line in response.text.strip().split("\n\n"):
            if line.startswith("data: "):
                events.append(json.loads(line[6:]))

        # Should have: status, status-clear, chunk, done
        assert len(events) == 4
        assert events[0] == {"type": "status", "content": "Searching catalog..."}
        assert events[1] == {"type": "status", "content": ""}
        assert events[2] == {"type": "chunk", "content": "Here are the results."}
        assert events[3]["type"] == "done"

    def test_stream_empty_message_422(self, test_client):
        """Empty message on streaming endpoint returns 422."""
        response = test_client.post("/api/chat/stream", json={
            "message": "",
        })
        assert response.status_code == 422


# ============================================
# Warmup Endpoint Tests
# ============================================

class TestWarmup:
    """Test POST /api/chat/warmup."""

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", False)
    def test_warmup_disabled(self, test_client):
        """Warmup returns skipped when AI chat is disabled."""
        response = test_client.post("/api/chat/warmup")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "skipped"
        assert "not enabled" in data["reason"]

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._LLM_PROVIDER", "claude")
    def test_warmup_not_ollama(self, test_client):
        """Warmup returns skipped when provider is not Ollama."""
        response = test_client.post("/api/chat/warmup")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "skipped"
        assert "claude" in data["reason"].lower()


# ============================================
# Provider Configuration Tests
# ============================================

class TestProviderConfig:
    """Test LLM provider selection logic."""

    @patch("api.routes.ai_chat.AI_CHAT_ENABLED", True)
    @patch("api.routes.ai_chat._LLM_PROVIDER", "ollama")
    @patch("api.routes.ai_chat._get_or_create_agent")
    def test_ollama_provider_used(self, mock_get_agent, test_client):
        """When LLM_PROVIDER=ollama, agent is created with ollama."""
        agent = _mock_agent()
        mock_get_agent.return_value = (agent, "ollama-session")

        response = test_client.post("/api/chat", json={
            "message": "hello",
        })
        assert response.status_code == 200

    def test_feature_flag_auto_detect(self):
        """Feature flag enables chat when provider is ollama (no API key)."""
        import api.routes.ai_chat as mod

        # Save originals
        orig_key = mod._API_KEY
        orig_provider = mod._LLM_PROVIDER
        orig_enabled = mod.AI_CHAT_ENABLED

        try:
            # Simulate: no API key, provider=ollama
            mod._API_KEY = ""
            mod._LLM_PROVIDER = "ollama"
            mod.AI_CHAT_ENABLED = bool(mod._API_KEY) or mod._LLM_PROVIDER == "ollama"
            assert mod.AI_CHAT_ENABLED is True

            # Simulate: no API key, no provider set, not ollama
            mod._API_KEY = ""
            mod._LLM_PROVIDER = ""
            mod.AI_CHAT_ENABLED = bool(mod._API_KEY) or mod._LLM_PROVIDER == "ollama"
            assert mod.AI_CHAT_ENABLED is False
        finally:
            # Restore
            mod._API_KEY = orig_key
            mod._LLM_PROVIDER = orig_provider
            mod.AI_CHAT_ENABLED = orig_enabled
