"""Excel formatting utilities with EDS brand styling.

Provides cell formatting, brand colors, and sheet finalization for
openpyxl workbooks generated by the report builder.
"""

from typing import Optional

try:
    from openpyxl.styles import (
        Alignment,
        Border,
        Font,
        PatternFill,
        Side,
    )
    HAS_OPENPYXL = True
except ImportError:
    HAS_OPENPYXL = False


class EDSColors:
    """EDS brand color palette."""

    PRIMARY = "1C1A83"       # Dark blue (headers)
    SECONDARY = "4A4890"     # Medium blue (subheaders)
    ACCENT = "B70C0D"        # Red (alerts)
    LIGHT_BLUE = "E8E7F4"   # Row tint
    WHITE = "FFFFFF"
    BLACK = "000000"
    DARK_GRAY = "404040"     # Body text
    MEDIUM_GRAY = "808080"   # Secondary text
    LIGHT_GRAY = "F5F5F5"   # Alternate row bg
    BORDER_GRAY = "CCCCCC"   # Cell borders
    SUCCESS_GREEN = "1E7E34"
    WARNING_YELLOW = "856404"


# Pre-built styles (only created if openpyxl is available)
if HAS_OPENPYXL:
    HEADER_FILL = PatternFill(start_color=EDSColors.PRIMARY, end_color=EDSColors.PRIMARY, fill_type="solid")
    HEADER_FONT = Font(name="Calibri", size=11, bold=True, color=EDSColors.WHITE)
    SUBHEADER_FILL = PatternFill(start_color=EDSColors.SECONDARY, end_color=EDSColors.SECONDARY, fill_type="solid")
    BODY_FONT = Font(name="Calibri", size=10, color=EDSColors.DARK_GRAY)
    ALT_ROW_FILL = PatternFill(start_color=EDSColors.LIGHT_GRAY, end_color=EDSColors.LIGHT_GRAY, fill_type="solid")
    THIN_BORDER = Border(
        left=Side(style="thin", color=EDSColors.BORDER_GRAY),
        right=Side(style="thin", color=EDSColors.BORDER_GRAY),
        top=Side(style="thin", color=EDSColors.BORDER_GRAY),
        bottom=Side(style="thin", color=EDSColors.BORDER_GRAY),
    )
    CENTER_ALIGN = Alignment(horizontal="center", vertical="center")
    LEFT_ALIGN = Alignment(horizontal="left", vertical="center", wrap_text=True)

# Format type → Excel number format
FORMAT_MAP = {
    "currency": "$#,##0.00",
    "percentage": "0.00%",
    "integer": "#,##0",
    "date": "MM/DD/YYYY",
    "datetime": "MM/DD/YYYY HH:MM",
}


def apply_cell_format(cell, format_type: str) -> None:
    """Apply a number format to a cell based on format type string."""
    if not HAS_OPENPYXL:
        return
    fmt = FORMAT_MAP.get(format_type)
    if fmt:
        cell.number_format = fmt


def style_header_row(ws, num_columns: int) -> None:
    """Apply EDS header styling to row 1 of a worksheet."""
    if not HAS_OPENPYXL:
        return
    for col in range(1, num_columns + 1):
        cell = ws.cell(row=1, column=col)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = CENTER_ALIGN
        cell.border = THIN_BORDER


def style_data_rows(ws, start_row: int, end_row: int, num_columns: int) -> None:
    """Apply alternating row styling to data rows."""
    if not HAS_OPENPYXL:
        return
    for row in range(start_row, end_row + 1):
        for col in range(1, num_columns + 1):
            cell = ws.cell(row=row, column=col)
            cell.font = BODY_FONT
            cell.border = THIN_BORDER
            cell.alignment = LEFT_ALIGN
            if row % 2 == 0:
                cell.fill = ALT_ROW_FILL


def finalize_sheet(ws) -> None:
    """Freeze header row and auto-size columns."""
    if not HAS_OPENPYXL:
        return
    ws.freeze_panes = "A2"
