"""Report builder — executes report plans and generates Excel workbooks.

Takes a ReportPlan (generated by the LLM), executes the SQL queries,
and produces a formatted .xlsx file with EDS brand styling.
"""

import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from agent.export.models import ReportPlan

logger = logging.getLogger(__name__)


class ReportBuilder:
    """Builds Excel reports from ReportPlan definitions."""

    def __init__(
        self,
        output_dir: str = "output",
        max_rows: int = 50_000,
        timeout: int = 120,
    ):
        self._output_dir = Path(output_dir)
        self._max_rows = max_rows
        self._timeout = timeout
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def build(
        self,
        report_plan: ReportPlan,
        connection_string: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Execute a report plan and generate an Excel file.

        Returns dict with: file_path, sheets_written, total_rows, elapsed_seconds, warnings.
        """
        from openpyxl import Workbook
        from agent.export.excel_formatter import (
            finalize_sheet,
            style_data_rows,
            style_header_row,
            apply_cell_format,
        )

        start = time.perf_counter()
        warnings = []

        conn_str = connection_string or self._build_connection_string()
        wb = Workbook()
        wb.remove(wb.active)  # Remove default sheet

        # Execute queries
        query_results: Dict[str, tuple] = {}
        for qdef in report_plan.queries:
            try:
                rows, columns = self._execute_query(qdef.sql, conn_str)
                if len(rows) > self._max_rows:
                    rows = rows[: self._max_rows]
                    warnings.append(
                        f"Query '{qdef.name}' truncated to {self._max_rows} rows"
                    )
                query_results[qdef.name] = (rows, columns)
            except Exception as e:
                logger.error("Query '%s' failed: %s", qdef.name, e)
                warnings.append(f"Query '{qdef.name}' failed: {e}")
                query_results[qdef.name] = ([], [])

        # Build sheets
        total_rows = 0
        sheets_written = 0

        for sdef in report_plan.sheets:
            if sdef.query not in query_results:
                warnings.append(f"Sheet '{sdef.name}': query '{sdef.query}' not found")
                continue

            rows, columns = query_results[sdef.query]
            ws = wb.create_sheet(title=sdef.title[:31])  # Excel 31-char limit

            # Write headers
            col_headers = [c.header for c in sdef.columns] if sdef.columns else columns
            for col_idx, header in enumerate(col_headers, 1):
                ws.cell(row=1, column=col_idx, value=header)

            # Write data
            for row_idx, row in enumerate(rows, 2):
                for col_idx, value in enumerate(row, 1):
                    cell = ws.cell(row=row_idx, column=col_idx, value=value)
                    # Apply format if column def exists
                    if sdef.columns and col_idx <= len(sdef.columns):
                        col_def = sdef.columns[col_idx - 1]
                        if col_def.format:
                            apply_cell_format(cell, col_def.format)

            # Apply styling
            num_cols = len(col_headers)
            style_header_row(ws, num_cols)
            if rows:
                style_data_rows(ws, 2, len(rows) + 1, num_cols)

            # Set column widths
            if sdef.columns:
                for col_idx, col_def in enumerate(sdef.columns, 1):
                    ws.column_dimensions[
                        chr(64 + col_idx) if col_idx <= 26 else "A"
                    ].width = col_def.width

            finalize_sheet(ws)
            total_rows += len(rows)
            sheets_written += 1

        # Save workbook
        filename = f"{report_plan.title.replace(' ', '_')}.xlsx"
        file_path = self._output_dir / filename
        wb.save(str(file_path))

        elapsed = time.perf_counter() - start

        return {
            "file_path": str(file_path),
            "sheets_written": sheets_written,
            "total_rows": total_rows,
            "elapsed_seconds": round(elapsed, 2),
            "warnings": warnings,
        }

    def _execute_query(self, sql: str, conn_str: str) -> tuple:
        import pyodbc

        with pyodbc.connect(conn_str, timeout=self._timeout) as conn:
            cursor = conn.cursor()
            cursor.execute(sql)
            if cursor.description is None:
                return [], []
            columns = [col[0] for col in cursor.description]
            rows = cursor.fetchmany(self._max_rows)
            return rows, columns

    def _build_connection_string(self) -> str:
        server = os.environ.get("DB_SERVER", "localhost")
        database = os.environ.get("DB_DATABASE_CATALOG", "EDS")
        username = os.environ.get("DB_USERNAME", "")
        password = os.environ.get("DB_PASSWORD", "")
        return (
            f"DRIVER={{ODBC Driver 17 for SQL Server}};"
            f"SERVER={server};DATABASE={database};"
            f"UID={username};PWD={password};"
        )
